logging:
  level:
    com.com.twentythree.peech: debug

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/peech_test"
    username: "root"
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true # data.sql? ???? ??
    hibernate:
      ddl-auto: ${DDL_ENV}
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  naver:
    client:
      secret: "a12698d1a30f4ba5b954fb585231ee53"
    stt:
      url: "https://clovaspeech-gw.ncloud.com/recog/v1/stt"
